# Generated by Django 5.0.7 on 2024-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockViva',
            fields=[
                ('jsonvivaresponse', models.TextField()),
                ('Specialization', models.CharField(max_length=100)),
                ('SpecializationDescription', models.TextField()),
                ('difficulty', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vivaid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
